[package]
name = "khonsu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
arrow = { version = "55", default-features = false }
thiserror = "2"
crossbeam-epoch = "0.9"
crossbeam-skiplist = "0.1"
crossbeam-queue = "0.3"
futures = { version = "0.3", features = ["executor"] }
parking_lot = "0.12"
