[package]
name = "khonsu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
ahash = "0.8"
arrow = { version = "55", default-features = false }
thiserror = "2"
futures = { version = "0.3", features = ["executor"] }
parking_lot = "0.12"
rocksdb = { version = "0.21", optional = true } # Add rocksdb dependency

[features]
default = []
twopc = ["omnipaxos", "rocksdb"] # Add rocksdb to the twopc feature

[dependencies.omnipaxos]
git = "https://github.com/haraldng/omnipaxos.git"
optional = true
